export interface EntityData {
Id: string;
PropertyCode: string;
EntityCode: string;
EntityName: string;
EntityTypeCode: string;
EntityUsageTypeCode: string;
StreetName: string;
CityName: string;
CountryName: string;
Latitude: string;
Longitude: string;
AreaSize: number;
PropertyAge: number;
TotalFloors: number;
TotalBasements: number;
TotalMezzanines: number;
TotalPodiums: number;
TotalParkingLots: number;
TotalStorageUnits: number;
TotalLoadingBays: number;
TotalEntrances: number;
TotalDestinaions: number;
TotalFacilities: number;
TotalRetailStores: number;
TotalStreets: number;
ServiceChargeType: string;
ResidentialServiceCharge: number;
CommercialServiceCharge: number;
// Active: boolean;
// CreatedDate: Date;
// ModifiedDate: Date;
CreatedBy: string;
}



// Id: string;
// PropertyCode: string;
// EntityCode: string;
// EntityName: string;
// EntityTypeCode: string;
// EntityUsageTypeCode: string;
// StreetName: string;
// CityName: string;
// CountryName: string;
// Latitude: string;
// Longitude: string;
// AreaSize: number;
// PropertyAge: number;
// TotalFloors: number;
// TotalBasements: number;
// TotalMezzanines: number;
// TotalPodiums: number;
// TotalParkingLots: number;
// TotalStorageUnits: number;
// TotalLoadingBays: number;
// TotalEntrances: number;
// TotalDestinaions: number;
// TotalFacilities: number;
// TotalRetailStores: number;
// TotalStreets: number;
// ServiceChargeType: string;
// ResidentialServiceCharge: number;
// CommercialServiceCharge: number;
// // Active: boolean;
// // CreatedDate: Date;
// // ModifiedDate: Date;
// CreatedBy: string;
